#!/bin/bash
set -e
flatpak install flathub -y app.drey.EarTag
flatpak install flathub -y app.xemu.xemu
flatpak install flathub -y com.adamcake.Bolt
flatpak install flathub -y com.belmoussaoui.Decoder
flatpak install flathub -y com.belmoussaoui.Obfuscate
flatpak install flathub -y com.feaneron.Boatswain
flatpak install flathub -y com.github.Rosalie241.RMG
flatpak install flathub -y com.markopejic.downloader
flatpak install flathub -y com.pokemmo.PokeMMO
flatpak install flathub -y com.rafaelmardojai.Blanket
flatpak install flathub -y com.richwhitehouse.BigPEmu
flatpak install flathub -y com.vixalien.sticky
flatpak install flathub -y com.vysp3r.ProtonPlus
flatpak install flathub -y dev.bragefuglseth.Keypunch
flatpak install flathub -y info.cemu.Cemu
flatpak install flathub -y io.edcd.EDMarketConnector
flatpak install flathub -y io.github.diegoivan.pdf_metadata_editor
flatpak install flathub -y io.github.fizzyizzy05.binary
flatpak install flathub -y io.github.idevecore.Valuta
flatpak install flathub -y io.github.realmazharhussain.GdmSettings
flatpak install flathub -y io.github.shiiion.primehack
flatpak install flathub -y io.gitlab.adhami3310.Converter
flatpak install flathub -y io.mgba.mGBA
flatpak install flathub -y md.obsidian.Obsidian
flatpak install flathub -y me.proton.Pass
flatpak install flathub -y net.kuribo64.melonDS
flatpak install flathub -y net.pcsx2.PCSX2
flatpak install flathub -y net.rpcs3.RPCS3
flatpak install flathub -y net.runelite.RuneLite
flatpak install flathub -y org.azahar_emu.Azahar
flatpak install flathub -y org.flycast.Flycast
flatpak install flathub -y org.gnome.gitlab.YaLTeR.VideoTrimmer
flatpak install flathub -y org.ppsspp.PPSSPP
flatpak install flathub -y org.signal.Signal
flatpak install flathub -y ro.go.hmlendea.DL-Desktop
flatpak install flathub -y se.sjoerd.Graphs
flatpak install flathub -y sh.ppy.osu
